unit TestuCalculadora;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, Vcl.Dialogs, Winapi.Windows, System.SysUtils, Vcl.ExtCtrls,
  uCalculadora, Vcl.Graphics, System.Variants, Winapi.Messages, Vcl.StdCtrls,
  Vcl.Controls, Vcl.Forms, System.Classes;

type
  // Test methods for class TFCalculadora

  TestTFCalculadora = class(TTestCase)
  strict private
    FFCalculadora: TFCalculadora;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestSomar;
    procedure TestSubtrair;
    procedure TestMultiplicar;
    procedure TestDividir;
  end;

implementation

procedure TestTFCalculadora.SetUp;
begin
  FFCalculadora := TFCalculadora.Create(nil);
end;

procedure TestTFCalculadora.TearDown;
begin
  FFCalculadora.Free;
  FFCalculadora := nil;
end;

procedure TestTFCalculadora.TestSomar;
var
  ReturnValue: Integer;
  ANumero2: Integer;
  ANumero1: Integer;
begin
  ANumero1 := 2;
  ANumero2 := 2;

  ReturnValue := FFCalculadora.Somar(ANumero1, ANumero2);

  CheckEquals(4, ReturnValue, 'A função somar falhou!');
end;

procedure TestTFCalculadora.TestSubtrair;
var
  ReturnValue: Integer;
  ANumero2: Integer;
  ANumero1: Integer;
begin
  ANumero1 := 2;
  ANumero2 := 2;

  ReturnValue := FFCalculadora.Subtrair(ANumero1, ANumero2);

  CheckEquals(0, ReturnValue, 'A função subtrair falhou!');
end;

procedure TestTFCalculadora.TestMultiplicar;
var
  ReturnValue: Integer;
  ANumero2: Integer;
  ANumero1: Integer;
begin
  ANumero1 := 2;
  ANumero2 := 3;

  ReturnValue := FFCalculadora.Multiplicar(ANumero1, ANumero2);

  CheckEquals(6, ReturnValue, 'A função multiplicar falhou!');
end;

procedure TestTFCalculadora.TestDividir;
var
  ReturnValue: Integer;
  ANumero2: Integer;
  ANumero1: Integer;
begin
  ANumero1 := 2;
  ANumero2 := 2;

  ReturnValue := FFCalculadora.Dividir(ANumero1, ANumero2);

  CheckEquals(1, ReturnValue, 'A função dividir falhou!');
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTFCalculadora.Suite);
end.

